### ISSUE TITLE
Add music upload

### ISSUE THREAD

**Issue by zarevskaya** [zusam/zusam#62] opened 2024-05-22 10:03 UTC
Hello, to begin with, thank you for this simple and practical application. I really like.

I added ALLOW_AUDIO_UPLOAD="true" and I can't send music after rebuilding the container. 

A suggestion?

**Comment by nrobinaubertin** [comment] 2024-05-27 15:04
Hello, thanks for your kind comment.  

The backend is not ready to receive music right now (but I had started to work on it in the https://github.com/zusam/zusam/tree/audio-upload branch). I'm not actively working on Zusam right now (since 6 months... Time flies) but it was one of the features at the top of my list.

I let you know when I'll do it (if you feel to code the backend yourself, I'll of course review your PR).

**Comment by nrobinaubertin** [comment] 2024-05-28 06:56
Related to https://github.com/zusam/zusam/issues/54

**Comment by zarevskaya** [comment] 2024-05-30 22:04
> Hello, thanks for your kind comment.
> 
> The backend is not ready to receive music right now (but I had started to work on it in the https://github.com/zusam/zusam/tree/audio-upload branch). I'm not actively working on Zusam right now (since 6 months... Time flies) but it was one of the features at the top of my list.
> 
> I let you know when I'll do it (if you feel to code the backend yourself, I'll of course review your PR).

Thanks for the answer :)

**Comment by nrobinaubertin** [comment] 2024-06-20 17:48
I'm closing this since it's a duplicate of the other issue asking for audio upload support.

**Closed by nrobinaubertin** 2024-06-20 17:48 UTC
Labels: enhancement
